---
pipeline:
    restore-cache:
        image: plugins/s3-cache:1
        pull: true
        endpoint: http://docker-node.tokyo.iiji.jp:9000
        access_key: DRONE
        secret_key: DRONEDRONE
        restore: true
        mount:
            - wheeldir

    test:
        image: python:${PYTHON_VERSION}
        environment:
            PIPENV_CACHE_DIR: wheeldir
        commands:
            - pip install pipenv
            - pipenv install --dev
            - pipenv run flake8 .
            - pipenv run pyflakes .
            - pipenv run nosetests --with-coverage --cover-package=exo -v test/

    rebuild-cache:
        image: plugins/s3-cache:1
        pull: true
        endpoint: http://docker-node.tokyo.iiji.jp:9000
        access_key: DRONE
        secret_key: DRONEDRONE
        rebuild: true
        mount:
            - wheeldir

    flush_cache:
        image: plugins/s3-cache:1
        pull: true
        endpoint: http://docker-node.tokyo.iiji.jp:9000
        access_key: DRONE
        secret_key: DRONEDRONE
        flush: true
        flush_age: 14

matrix:
    PYTHON_VERSION:
        - "3.6.7"
        - "3.6.6"
        - "3.6.5"
