---
pipeline:
    restore-cache:
        image: plugins/s3-cache:1
        pull: true
        endpoint: http://docker-node.tokyo.iiji.jp:9000
        access_key: DRONE
        secret_key: DRONEDRONE
        restore: true
        mount:
            - wheeldir

    build:
        # image: python:${PYTHON_VERSION}
        image: python:3.6.5
        commands:
            - pip install --upgrade pip setuptools wheel
            - pip wheel -r requirement/dev.txt --wheel-dir=wheeldir --find-links=wheeldir
            - pip install --no-index --find-links=wheeldir -r requirement/dev.txt
            - flake8 .
            - pyflakes .
            - nosetests --with-coverage -v test/
        when:
            branch: [master, test]


    rebuild-cache:
        image: plugins/s3-cache:1
        pull: true
        endpoint: http://docker-node.tokyo.iiji.jp:9000
        access_key: DRONE
        secret_key: DRONEDRONE
        rebuild: true
        mount:
            - wheeldir

    flush_cache:
        image: plugins/s3-cache:1
        pull: true
        endpoint: http://docker-node.tokyo.iiji.jp:9000
        access_key: DRONE
        secret_key: DRONEDRONE
        flush: true
        flush_age: 14

notify:
    irc:
        prefix: build
        nick: drone
        channel: aps-mail
        host: irc.iiji.jp
        port: 6667
        enable_tls: true
        debug: true
#        when:
#            status: success

# matrix:
#     PYTHON_VERSION:
#         - latest
#         - "3.6.5"
