---
language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev
# command to run tests
script:
  - nosetests --with-coverage --cover-package=exo --cover-xml
# Push the results back to codecov
after_success:
  - codecov
